import '@/styles/globals.css'
import type { Metadata } from 'next'
import Navigation from '@/components/Navigation/page';
import Footer from '@/components/Footer/page';
import ThemeProvider from  "@/Provider/ThemeProvider"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {children: React.ReactNode}) 

{
  return (
    <html lang="en">
      <body>
        <ThemeProvider >
        <header className={`container header-container`}>
          <div className={'header'}>
          header
          </div>

        </header>

        <nav className={`container nav-container`}>
            <Navigation className="nav" />
        </nav>

        <main className={`container main-container`}>
          <div className={'main'}>
          {children}
          </div>
        </main>

        <footer className={`container footer-container`}>
          <Footer className="footer"/>
        </footer>
        </ThemeProvider>
        </body>
    </html>
  )
}
